import { defineConfig } from "vite-plus";

export default defineConfig({
	fmt: {
		useTabs: true,
		tabWidth: 2,
		printWidth: 80,
		singleQuote: false,
		jsxSingleQuote: false,
		quoteProps: "as-needed",
		trailingComma: "all",
		semi: true,
		arrowParens: "always",
		bracketSameLine: false,
		bracketSpacing: true,
		ignorePatterns: [
			"**/.next",
			"**/dist",
			"**/dev-dist",
			"**/.zed",
			"**/.vscode",
			"**/routeTree.gen.ts",
			"**/worker-configuration.d.ts",
			"**/src-tauri",
			"**/.nuxt",
			"bts.jsonc",
			"**/.expo",
			"**/.wrangler",
			"**/.alchemy",
			"**/.svelte-kit",
			"**/.source",
			"**/node_modules",
			"**/.git",
			"**/coverage",
			"**/build",
			"**/.cache",
			"**/.env*",
			"**/drizzle",
			"**/migrations",
		],
	},
	lint: {
		plugins: ["react", "typescript", "unicorn", "oxc", "import", "jsx-a11y"],
		categories: {
			correctness: "error",
		},
		env: {
			builtin: true,
			browser: true,
			node: true,
			es2024: true,
		},
		settings: {
			react: {
				version: "19.1.0",
			},
		},
		rules: {
			"no-unused-vars": [
				"error",
				{
					ignoreRestSiblings: true,
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
					caughtErrorsIgnorePattern: "^_",
					destructuredArrayIgnorePattern: "^_",
				},
			],
			"react/exhaustive-deps": "warn",
			"react/self-closing-comp": "error",
			"no-param-reassign": "error",
			"default-param-last": "error",
			"no-else-return": "error",
			"no-useless-concat": "error",
			"typescript/prefer-as-const": "error",
			"typescript/prefer-enum-initializers": "error",
			"typescript/no-inferrable-types": "error",
			"unicorn/prefer-number-properties": "error",
		},
		ignorePatterns: [
			"**/.next",
			"**/dist",
			"**/dev-dist",
			"**/.zed",
			"**/.vscode",
			"**/routeTree.gen.ts",
			"**/worker-configuration.d.ts",
			"**/src-tauri",
			"**/.nuxt",
			"bts.jsonc",
			"**/.expo",
			"**/.wrangler",
			"**/.alchemy",
			"**/.svelte-kit",
			"**/.source",
			"**/node_modules",
			"**/.git",
			"**/coverage",
			"**/build",
			"**/.cache",
			"**/.env*",
			"**/drizzle",
			"**/migrations",
		],
		options: {
			typeAware: true,
			typeCheck: true,
		},
	},
	staged: {
		"*.{js,ts,cjs,mjs,d.cts,d.mts,d.ts,jsx,tsx}": "vp lint --fix",
		"*.{js,ts,cjs,mjs,d.cts,d.mts,d.ts,jsx,tsx,json,jsonc,css}": "vp fmt",
	},
});
